[build-system]
requires = ["setuptools==83.0.0", "wheel==0.46.2"]
build-backend = "setuptools.build_meta"

[project]
name = "nuv-agent"
version = "0.1.120"
description = "Nuvion on-device agent"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "python-dotenv",
  "pyserial",
  "qrcode",
  "websockets",
  "stomper",
  "aiohttp",
  "cryptography>=50,<51",
]

[project.optional-dependencies]
zsad = [
  "torch==2.10.0",
  "numpy==2.4.2",
  "transformers==5.16.1",
  "huggingface-hub==1.29.0",
  "hf-xet==1.6.0",
  "tokenizers==0.23.1",
  "safetensors==0.8.0",
  "Pillow==12.1.0",
  "sentencepiece==0.2.2",
  "protobuf==7.36.1",
]
triton = [
  "tritonclient[http]",
  "opencv-python",
]
depthai = [
  "depthai==2.32.0.0",
]

[project.scripts]
nuv-agent = "nuvion_app.cli:main"
nuvion-updater = "nuvion_updater.daemon:main"

[tool.setuptools]
packages = [
  "nuvion_app",
  "nuvion_app.inference",
  "nuvion_app.agent",
  "nuvion_app.runtime",
  "nuvion_updater",
]
include-package-data = true

[tool.setuptools.package-data]
nuvion_app = ["config_template.env"]
