"""Fleet features that require live runtime proof, never a static profile."""

PLATFORM_ADMIN_CONTEXT = "PLATFORM_ADMIN"
PLATFORM_ADMIN_CAPABILITY = "fleet.auth.platform_admin.v1"
RUNTIME_AUTHORIZATION_CAPABILITIES = frozenset({PLATFORM_ADMIN_CAPABILITY})
SIGLIP_MODEL_CONFIG_CAPABILITY = "command.config.model.siglip.v1"
VISUALAD_HTP_MODEL_CONFIG_CAPABILITY = "command.config.model.visualad_htp.v1"
RUNTIME_ONLY_FLEET_CAPABILITIES = RUNTIME_AUTHORIZATION_CAPABILITIES | {
    SIGLIP_MODEL_CONFIG_CAPABILITY,
    VISUALAD_HTP_MODEL_CONFIG_CAPABILITY,
}
